name: Validate Postman Collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Newman
      run: npm install -g newman

    - name: Validate Collection
      run: |
        for file in collections/*.json; do
          newman run "$file" --env-var "baseUrl=https://example.com" --env-var "companyId=test" --delay-request 100
        done
